[network]
name = "testnet"
chain = "local"
token-symbol = "TST"
token-decimal = 12

# For bootstrapping frontier-based chains
[frontier.evm.accounts]
"0x1000000000000000000000000000000000000001" = { balance = "0xd3c21bcecceda1000000", code = [
    0,
], nonce = "0x1", storage = {} }
"0x6be02d1d3665660d22ff9624b7be0551ee1ac91b" = { balance = "0xffffffffffffffffffffffffffffffff", code = [
], nonce = "0x0", storage = {} }
"0xd43593c715fdd31c61141abd04a99fd6822c8558" = { balance = "0xffffffffffffffffffffffffffffffff", code = [
], nonce = "0x0", storage = {} }

[frontier.evmChainId]
chainId = 42

[[nodes]]
name = "elizabeth"
p2p-port = 30333
rpc-port = 9943
prometheus-port = 9613
balance = 4000

[[nodes]]
name = "rachel"
p2p-port = 30334
rpc-port = 9944
prometheus-port = 9614
balance = 5000

[[nodes]]
name = "skyler"
p2p-port = 30336
rpc-port = 9946
prometheus-port = 9616
