name: Build and Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
env:
  PYTHON_VERSION: "3.10"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create venv and install dependencies
        run: |
            python -m venv .venv
            .venv/bin/pip install .
            .venv/bin/pip install twine build

      - name: Build source and wheel distribution
        run: |
          source .venv/bin/activate # Activate the venv
          python -m build .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pysubnet
          path: dist/*

  publish-testpypi:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pysubnet
          path: dist

      - name: Upload to GitHub Release (Draft)
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/* # Corrected artifacts path
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          body: "Draft release ${{ github.ref_name }} of pysubnet"
          draft: true
          prerelease: false

      - name: Install/Upgrade Twine and Packaging
        run: python -m pip install --upgrade twine packaging # Upgrade both

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          twine upload --repository testpypi dist/*

  publish-pypi:
    needs: publish-testpypi
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pysubnet
          path: dist

      - name: Install/Upgrade Twine and Packaging
        run: python -m pip install --upgrade twine packaging # Upgrade both

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*

      - name: Finalize GitHub Release (Undraft)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}